### PR TITLE
refactor: light service refactor & bug fixes

### LINKED ISSUE #618: bug: sky light calculation is wrong
```
x
A
x
x
x
xxxxx
```

Expected sky light value of A: 14
Actual value: 11

### PR DESCRIPTION
**Pull request by smartcmd**
This PR refactored the current light service implementation. Now the tasks in light service are divided into three parts, and each part has an independent thread to handle. This should make the light service much quicker since we now have three threads to calculate instead of just one.

We also fixed sky light calculation in this PR. To be detailed, the light service now can handle horizontal propagation of skylight correctly.

Closed #618

### CODE REVIEW

File: server/src/main/java/org/allaymc/server/world/service/LightDataAccessor.java [hunk 1]
```diff
@@ -0,0 +1,20 @@
+package org.allaymc.server.world.service;
+
+/**
+ * @author daoge_cmd
+ */
+public interface LightDataAccessor {
```
Comment (IWareQ) [inline server/src/main/java/org/allaymc/server/world/service/LightDataAccessor.java:6]: Add JavaDoc for this interface methods

**Review by IWareQ — APPROVED** [review]
